package com.project.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.project.controller.User;
import com.project.controller.UserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/ranks") // This means URL's start with /demo (after Application path)
public class MainController {
	 // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private UserRepository userRepository;
	
//	@GetMapping(path="/add") // Map ONLY GET Requests
//	public @ResponseBody String addNewUser (@RequestParam String name
//			, @RequestParam String email) {
//		// @ResponseBody means the returned String is the response, not a view name
//		// @RequestParam means it is a parameter from the GET or POST request
//		
//		User n = new User();
//		n.setName(name);
//		n.setEmail(email);
//		userRepository.save(n);
//		return "Saved";
//	}
	
//	@GetMapping(path="/add") // Map ONLY GET Requests
//	public @ResponseBody String addNewCharData (@RequestParam CharacterInfo charInfo) {
//		// @ResponseBody means the returned String is the response, not a view name
//		// @RequestParam means it is a parameter from the GET or POST request
//		
////		User n = new User();
////		n.setName(name);
////		n.setEmail(email);
//		userRepository.save(charInfo);
//		return "Saved";
//	}
//	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<CharacterInfo> getAllCharInfo() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
//}
}
