# Current League Names
employee-service:
   filter:
     resource:
       properties:
         LEAGUE1: Synthesis
         LEAGUE2: Hardcore Synthesis
         LEAGUE3: SSF Synthesis
         LEAGUE4: SSF Synthesis HC
        
